### ISSUE TITLE
com.gzsll.jsbridge.WVJBWebView is compile error

### ISSUE THREAD

**Issue by BongJaeChoi** [gzsll/WebViewJavascriptBridge#11]
I tried

![2016-11-23 4 55 11](https://cloud.githubusercontent.com/assets/8946333/20554198/a47b4ad6-b19d-11e6-8b44-5954ccfab91a.png)

I faced error 
>java.lang.NoSuchMethodError: com.gzsll.jsbridge.WVJBWebView.getSettings()Landroid/webkit/WebSettings;
	at com.gzsll.jsbridge.WVJBWebView.init(WVJBWebView.java:61)
	at com.gzsll.jsbridge.WVJBWebView.<init>(WVJBWebView.java:51)
	at sun.reflect.GeneratedConstructorAccessor601.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$53(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

What should I do?? What a problem???

please tell me in English

**Comment by gzsll** [comment]
it seems cause by ` getSettings().setJavaScriptEnabled(true);`,what's your device?

**Comment by BongJaeChoi** [comment]
Thanks for comment.
Still showing error but app is  working. 
- Environment : Android studio 2.2.2 , mac.
- test device : Redmi 3s

**Comment by gzsll** [comment]
working correctly?

**Comment by BongJaeChoi** [comment]
Fortunately, yes..
